# Generated by Django 5.2.7 on 2025-10-31 07:10

import django.db.models.deletion
import progress.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('planned_task', models.TextField(help_text='Admin: Enter the tasks for the day here.')),
                ('admin_remarks', models.TextField(blank=True, help_text='Admin: Enter your remarks after SCO submission.')),
                ('actual_progress', models.TextField(blank=True, help_text='SCO: Describe the actual work done.')),
                ('file_upload', models.FileField(blank=True, help_text='SCO: Upload any relevant files or photos.', null=True, upload_to=progress.models.progress_file_upload_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted for Review'), ('REVIEWED', 'Reviewed and Closed')], default='PENDING', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='projects.project')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
