# Generated by Django 5.2.7 on 2025-12-11 12:39

import progress.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('planned_task', models.TextField(help_text='Admin: Enter the tasks for the day here.')),
                ('admin_remarks', models.TextField(blank=True, help_text='Admin: Enter your remarks after SCO submission.')),
                ('actual_progress', models.TextField(blank=True, help_text='SCO: Describe the actual work done.')),
                ('file_upload', models.FileField(blank=True, help_text='SCO: Upload any relevant files or photos.', null=True, upload_to=progress.models.progress_file_upload_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted for Review'), ('REVIEWED', 'Reviewed and Closed')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Select the Monday of the week for this report.')),
                ('planned_task', models.TextField(help_text='Admin: Enter the main goals for the week.')),
                ('admin_remarks', models.TextField(blank=True, help_text='Admin: Enter your review for the week.')),
                ('actual_progress', models.TextField(blank=True, help_text='SCO: Summarize the work done this week.')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to=progress.models.weekly_progress_file_upload_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted for Review'), ('REVIEWED', 'Reviewed and Closed')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-week_start_date'],
            },
        ),
    ]
