# Generated by Django 5.2.7 on 2025-10-31 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        ('projects', '0002_remove_project_assigned_sco_project_assigned_scos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The SCO this specific task is assigned to.', limit_choices_to={'role': 'sco'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together={('project', 'date', 'assigned_to')},
        ),
    ]
