# Generated by Django 5.2.7 on 2025-12-11 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='assigned_to',
            field=models.ForeignKey(help_text='The SCO this specific task is assigned to.', limit_choices_to={'role': 'sco'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='projects.project'),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='assigned_to',
            field=models.ForeignKey(help_text='Assign to a specific SCO, or leave blank for a general weekly report.', limit_choices_to={'role': 'sco'}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='projects.project'),
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_weekly_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together={('project', 'date', 'assigned_to')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyprogress',
            unique_together={('project', 'week_start_date', 'assigned_to')},
        ),
    ]
