# Generated by Django 5.2.7 on 2025-10-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_dailyprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together=set(),
        ),
    ]
