# Generated by Django 5.2.7 on 2025-10-31 13:31

import django.db.models.deletion
import progress.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_alter_dailyprogress_unique_together'),
        ('projects', '0002_remove_project_assigned_sco_project_assigned_scos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Select the Monday of the week for this report.')),
                ('planned_task', models.TextField(help_text='Admin: Enter the main goals for the week.')),
                ('admin_remarks', models.TextField(blank=True, help_text='Admin: Enter your review for the week.')),
                ('actual_progress', models.TextField(blank=True, help_text='SCO: Summarize the work done this week.')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to=progress.models.weekly_progress_file_upload_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted for Review'), ('REVIEWED', 'Reviewed and Closed')], default='PENDING', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='projects.project')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_weekly_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('project', 'week_start_date')},
            },
        ),
    ]
