# Generated by Django 5.2.7 on 2025-10-31 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_weeklyprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklyprogress',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Assign to a specific SCO, or leave blank for a general weekly report.', limit_choices_to={'role': 'sco'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
