# Generated by Django 5.2.7 on 2025-11-04 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_alter_weeklyprogress_unique_together_and_more'),
        ('projects', '0002_remove_project_assigned_sco_project_assigned_scos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='assigned_to',
            field=models.ForeignKey(help_text='The SCO this specific task is assigned to.', limit_choices_to={'role': 'sco'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklyprogress',
            name='assigned_to',
            field=models.ForeignKey(help_text='Assign to a specific SCO, or leave blank for a general weekly report.', limit_choices_to={'role': 'sco'}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together={('project', 'date', 'assigned_to')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyprogress',
            unique_together={('project', 'week_start_date', 'assigned_to')},
        ),
    ]
