# Generated by Django 5.2.7 on 2025-12-11 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiries', '0001_initial'),
        ('projects', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_scos',
            field=models.ManyToManyField(blank=True, help_text='Assign one or more Site Coordination Officers to this project.', limit_choices_to={'role': 'sco'}, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='enquiries.customer'),
        ),
        migrations.AddField(
            model_name='project',
            name='quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='milestonephase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_phases', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_items', to='projects.project'),
        ),
    ]
