# Generated by Django 5.2.3 on 2025-10-31 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_sco',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_scos',
            field=models.ManyToManyField(blank=True, help_text='Assign one or more Site Coordination Officers to this project.', limit_choices_to={'role': 'sco'}, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
