# Generated by Django 5.2.7 on 2025-12-11 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.PositiveIntegerField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('contractor_name', models.CharField(blank=True, max_length=255)),
                ('subcontractor_name', models.CharField(blank=True, max_length=255, verbose_name='Subcontractor Name')),
                ('chronological_account', models.TextField(blank=True, help_text='8:00 AM to 6:00 PM - Describe the work done.')),
                ('activities_for_next_day', models.TextField(blank=True)),
                ('issues_encountered', models.TextField(blank=True, verbose_name='Force Work / Changes Encountered / Safety Issues')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='Equipment')),
                ('day_count', models.PositiveIntegerField(default=0, verbose_name='Day')),
                ('night_count', models.PositiveIntegerField(default=0, verbose_name='Night')),
            ],
        ),
        migrations.CreateModel(
            name='ManpowerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(max_length=100, verbose_name='Staffs & Labor')),
                ('day_count', models.PositiveIntegerField(default=0, verbose_name='Day')),
                ('night_count', models.PositiveIntegerField(default=0, verbose_name='Night')),
            ],
        ),
        migrations.CreateModel(
            name='SubcontractorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(max_length=100, verbose_name='Staffs & Labor')),
                ('day_count', models.PositiveIntegerField(default=0, verbose_name='Day')),
                ('night_count', models.PositiveIntegerField(default=0, verbose_name='Night')),
            ],
        ),
    ]
