# Generated by Django 5.2.7 on 2025-12-11 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='projects.project'),
        ),
        migrations.AddField(
            model_name='equipmentlog',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_logs', to='reports.dailyreport'),
        ),
        migrations.AddField(
            model_name='manpowerlog',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_logs', to='reports.dailyreport'),
        ),
        migrations.AddField(
            model_name='subcontractorlog',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_logs', to='reports.dailyreport'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('project', 'date')},
        ),
    ]
