# Generated by Django 5.2.7 on 2025-12-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trn_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
