# Generated by Django 5.2.7 on 2025-11-06 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='section',
        ),
        migrations.AddField(
            model_name='quotation',
            name='quote_type',
            field=models.CharField(choices=[('DESIGN', 'Design'), ('FITOUT', 'Fitout')], default='DESIGN', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='enquiries.enquiry'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('enquiry', 'quote_type')},
        ),
    ]
